# Generated by Django 4.1.3 on 2022-11-23 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='post_number',
        ),
    ]
